### ISSUE TITLE
ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by VusalIs** [workos/workos-node#995]
Hi,

I use workos-node v6.0.2, and get `ReferenceError: crypto is not defined` when I use `constructEvent` or `verifyHeader` functions. 

Sample code:

```
const workos = new WorkOS(process.env.WORKOS_API_KEY);
app.post("/api/auth/events", async (req, res) => {
  const payload = req.body;
  const sigHeader = req.headers["workos-signature"] as string;

  try {
    const webhook = await workos.webhooks.verifyHeader({
      payload,
      sigHeader,
      secret: process.env.WEBHOOK_SECRET,
    });
  } catch (error) {
    console.log(error);
  }

  return res.status(200);
});
```

Could you help me?

**Comment by PaulAsjes** [comment]
Hi @VusalIs, in what JS environment are you running this? Is this in Node (if so, what version?) or in a different runtime like Cloudflare Workers?

**Comment by VusalIs** [comment]
It is Node v18.19.1

**Comment by PaulAsjes** [comment]
Hi @VusalIs and @khaliqgant, this is happening because v6 of the Node SDK switched to using the Web Crypto API over the native Node implementation. As such it's only compatible with Node versions 19 and up. If you can I recommend upgrading to the latest LTS of Node, which is currently v20.

If that's not an option, you can still use [v5.2.0](https://github.com/workos/workos-node/releases/tag/v5.2.0) of this SDK which will work in older versions of Node.

**Comment by khaliqgant** [comment]
Got it, thanks. We’ll have to use the v5.2.0 version. Main issue with that is that it looks like TS types aren’t exported 😕

**Comment by VusalIs** [comment]
Same here, we have to downgrade the version. Thanks
